apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
  namespace: aws-simulation
  labels:
    app: zeecrumb-backend
    tier: api
    cloud-simulation: aws
spec:
  containers:
    - name: backend
      image: zeecrumb-backend:sim
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 5000
      env:
        - name: SIM_REGION
          value: aws-simulation
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: DATABASE_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: JWT_SECRET
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: MONGO_URI
      readinessProbe:
        httpGet:
          path: /health
          port: 5000
        initialDelaySeconds: 15
        periodSeconds: 10
      livenessProbe:
        httpGet:
          path: /health
          port: 5000
        initialDelaySeconds: 30
        periodSeconds: 20
