apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: gcp-simulation
  labels:
    app: zeecrumb-frontend
    cloud-simulation: gcp
spec:
  type: ClusterIP
  selector:
    app: zeecrumb-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
